export default {

  "login": "jasonhu777",
  "id": 36783602,
  "node_id": "MDQ6VXNlcjM2NzgzNjAy",
  "avatar_url": "https://avatars3.githubusercontent.com/u/36783602?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/jasonhu777",
  "html_url": "https://github.com/jasonhu777",
  "followers_url": "https://api.github.com/users/jasonhu777/followers",
  "following_url": "https://api.github.com/users/jasonhu777/following{/other_user}",
  "gists_url": "https://api.github.com/users/jasonhu777/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/jasonhu777/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/jasonhu777/subscriptions",
  "organizations_url": "https://api.github.com/users/jasonhu777/orgs",
  "repos_url": "https://api.github.com/users/jasonhu777/repos",
  "events_url": "https://api.github.com/users/jasonhu777/events{/privacy}",
  "received_events_url": "https://api.github.com/users/jasonhu777/received_events",
  "type": "User",
  "site_admin": false,
  "name": "awejason",
  "company": null,
  "blog": "jasonhuportfolio.web.app",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2018-02-24T05:24:34Z",
  "updated_at": "2021-01-09T04:03:34Z"
}
